DROP TABLE IF EXISTS TRANSACTION;
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS CUSTOMER;


CREATE TABLE IF NOT EXISTS CUSTOMER (
  ID int NOT NULL auto_increment,
  NIF varchar(9) NOT NULL,
  NAME varchar(15) NOT NULL,
  SURNAME varchar(15) NOT NULL,
  CREATION_DATE timestamp NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ACCOUNT (
  ID int NOT NULL auto_increment,
  ID_CUSTOMER int NOT NULL,
  IBAN varchar(34) NOT NULL,
  BALANCE double NOT NULL,  
  PRIMARY KEY (ID),  CONSTRAINT FK_CUSTOMER FOREIGN KEY (ID_CUSTOMER) references CUSTOMER(ID)
);

CREATE TABLE IF NOT EXISTS TRANSACTION (
  ID int NOT NULL auto_increment,
  ID_ACCOUNT int NOT NULL,
  SOURCE varchar(34) NOT NULL,
  TARGET varchar(34) NOT NULL,
  TYPE varchar(15) NOT NULL,
  CREATION_DATE timestamp NOT NULL,
  AMMOUNT double NOT NULL,  
  PRIMARY KEY (ID),
  CONSTRAINT FK_ACCOUNT FOREIGN KEY (ID_ACCOUNT) references ACCOUNT(ID)
);






