DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER (
  ID int NOT NULL,
  NIF varchar(3) NOT NULL,
  NAME varchar(3) NOT NULL,
  SURNAME varchar(3) NOT NULL,
  CREATION_DATE timestamp NOT NULL,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNT (
  ID int NOT NULL,
  ID_CUSTOMER int NOT NULL,
  IBAN varchar(34) NOT NULL,
  BALANCE double NOT NULL,  
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_CUSTOMER) references CUSTOMER(ID)
);

DROP TABLE IF EXISTS TRANSACTION;

CREATE TABLE TRANSACTION (
  ID int NOT NULL,
  ID_ACCOUNT int NOT NULL,
  TYPE varchar(15) NOT NULL,
  BALANCE double NOT NULL,  
  CREATION_DATE timestamp NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_ACCOUNT) references ACCOUNT(ID)
);