CREATE TABLE IF NOT EXISTS CUSTOMER (
  ID int NOT NULL,
  NIF varchar(3) NOT NULL,
  NAME varchar(3) NOT NULL,
  SURNAME varchar(3) NOT NULL,
  CREATION_DATE timestamp NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ACCOUNT (
  ID int NOT NULL,
  ID_CUSTOMER int NOT NULL,
  IBAN varchar(34) NOT NULL,
  BALANCE double NOT NULL,  
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_CUSTOMER) references CUSTOMER(ID)
);

CREATE TABLE IF NOT EXISTS TRANSACTION (
  ID int NOT NULL,
  ID_ACCOUNT int NOT NULL,
  SOURCE varchar(34) NOT NULL,
  TARGET varchar(34) NOT NULL,
  TYPE varchar(15) NOT NULL,
  CREATION_DATE timestamp NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_ACCOUNT) references ACCOUNT(ID)
);






